from enum import Enum


class AuthException(str, Enum):
    VERIFY_TOKEN_EXPIRED = "VERIFY_TOKEN_EXPIRED"
    VERIFY_USER_BAD_TOKEN = "VERIFY_USER_BAD_TOKEN"
    VERIFY_USER_NOT_FOUND = "VERIFY_USER_NOT_FOUND"
    USER_ALREADY_EXIST = "USER_ALREADY_EXIST"
    INCORRECT_PASSWORD = "INCORRECT_PASSWORD"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_SUCCESSFULLY_REGISTER = "USER_SUCCESSFULLY_REGISTER"
