name: Testing todo_example

on: push

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run black check
      run: poetry run black --check .
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      uses: chartboost/ruff-action@v1
    - name: Run ruff check
      run: poetry run ruff check .

  pytest:
    runs-on: ubuntu-latest
    services:

      todo_example-db:
        image: postgres:13.8-bullseye
        env:
          POSTGRES_PASSWORD: todo_example
          POSTGRES_USER: todo_example
          POSTGRES_DB: todo_example
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run pytest check
      run: poetry run pytest -vv --cov="todo_example" .
      env:
        TODO_EXAMPLE_HOST: "0.0.0.0"
        TODO_EXAMPLE_DB_HOST: localhost
